export const ACTION_BALANCE="ACTION_BALANCE";
export const ACTION_INCOME="ACTION_INCOME";
export const ACTION_EXPANCE="ACTION_EXPANCE";
export const ACTION_HISTORY="ACTION_HISTORY";
export const ACTION_ADD_TRANSICTION="ACTION_ADD_TRANSICTION";


